# Generated by Django 6.0.7 on 2026-08-06 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(verbose_name='Direccion IPv4')),
                ('mac', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Formato MAC invalido. Use XX:XX:XX:XX:XX:XX', regex='^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$')], verbose_name='Direccion MAC')),
                ('activo', models.BooleanField(default=True, help_text='Equipo habilitado en el sistema')),
                ('estado_conexion', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='inactivo', max_length=20)),
                ('ultima_actividad', models.DateTimeField(blank=True, null=True)),
                ('ultimo_ping', models.DateTimeField(blank=True, null=True)),
                ('posicion_fisica', models.CharField(blank=True, max_length=20)),
                ('tiene_relay', models.BooleanField(default=False)),
                ('relay_gpio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consumo_watts', models.FloatField(default=250.0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='laboratorio.laboratorio')),
            ],
            options={
                'db_table': 'equipos_equipo',
                'ordering': ['laboratorio', 'nombre'],
                'unique_together': {('laboratorio', 'ip')},
            },
        ),
        migrations.CreateModel(
            name='EventoConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conexion', 'Conexion'), ('desconexion', 'Desconexion'), ('suspension', 'Suspension'), ('apagado', 'Apagado'), ('encendido', 'Encendido')], max_length=20)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_conexion', to='equipos.equipo')),
            ],
            options={
                'db_table': 'equipos_evento_conexion',
                'ordering': ['-registrado_en'],
            },
        ),
    ]
