# Generated by Django 6.0.6 on 2026-06-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado_conexion',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', max_length=10),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ultimo_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
