# Generated by Django 6.0.6 on 2026-06-21 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_estado_conexion_equipo_ultimo_ping'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conexion', 'Conexión'), ('desconexion', 'Desconexión')], max_length=12)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_conexion', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Evento de conexión',
                'verbose_name_plural': 'Eventos de conexión',
                'ordering': ['-registrado_en'],
            },
        ),
    ]
