# Generated by Django 6.0.6 on 2026-06-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAutomatizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('condicion', models.CharField(choices=[('inactividad_minutos', 'Minutos sin movimiento (PIR)')], max_length=50)),
                ('valor_umbral', models.IntegerField(help_text='Ej: 30 (minutos)')),
                ('accion_a_ejecutar', models.CharField(help_text='Ej: apagar_aire, apagar_luces', max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regla de Automatización',
                'verbose_name_plural': 'Reglas de Automatización',
            },
        ),
    ]
