# Generated by Django 6.0.6 on 2026-06-18 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoOcupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ocupado', 'Aula Ocupada'), ('vacio', 'Aula Vacía')], max_length=10)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='dispositivos.dispositivo')),
            ],
            options={
                'verbose_name': 'Evento de ocupación',
                'verbose_name_plural': 'Eventos de ocupación',
                'ordering': ['-registrado_en'],
            },
        ),
    ]
