# Generated by Django 6.0.7 on 2026-08-06 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoOcupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ocupado', 'Ocupado'), ('vacio', 'Vacío')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_ocupacion', to='dispositivos.dispositivo')),
            ],
            options={
                'verbose_name': 'Evento de Ocupación',
                'verbose_name_plural': 'Eventos de Ocupación',
                'db_table': 'ocupacion_evento_ocupacion',
                'ordering': ['-timestamp'],
            },
        ),
    ]
