# Generated by Django 6.0.7 on 2026-08-06 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('suspender_equipo', 'Suspender Equipo'), ('apagar_equipo', 'Apagar Equipo'), ('encender_relay', 'Encender por Relay'), ('encender_luces', 'Encender Iluminación'), ('apagar_luces', 'Apagar Iluminación')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutado', 'Ejecutado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('ip_equipo_destino', models.GenericIPAddressField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ejecutado_en', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='dispositivos.dispositivo')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Comando',
                'verbose_name_plural': 'Comandos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
