# Generated by Django 6.0.6 on 2026-06-24 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('encender_aire', 'Encender Aire Acondicionado'), ('apagar_aire', 'Apagar Aire Acondicionado'), ('encender_luces', 'Encender Luces'), ('apagar_luces', 'Apagar Luces'), ('reiniciar', 'Reiniciar Dispositivo')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutado', 'Ejecutado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ejecutado_en', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='dispositivos.dispositivo')),
            ],
            options={
                'verbose_name': 'Comando',
                'verbose_name_plural': 'Comandos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
