# Generated by Django 6.0.6 on 2026-07-02 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
        ('dispositivos', '0001_initial'),
        ('equipos', '0003_eventoconexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comando',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='comando',
            name='ip_equipo_destino',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comando',
            name='resultado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comando',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='dispositivos.dispositivo'),
        ),
        migrations.AlterField(
            model_name='comando',
            name='tipo_accion',
            field=models.CharField(choices=[('suspender_equipo', 'Suspender Equipo'), ('apagar_equipo', 'Apagar Equipo'), ('encender_relay', 'Encender por Relay'), ('encender_luces', 'Encender Iluminación'), ('apagar_luces', 'Apagar Iluminación')], max_length=50),
        ),
    ]
