# Generated by Django 6.0.7 on 2026-08-06 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('capacidad', models.PositiveIntegerField(help_text='Número de equipos del laboratorio', validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('horario_apertura', models.TimeField(default='07:00')),
                ('horario_cierre', models.TimeField(default='21:00')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'laboratorio_laboratorio',
                'ordering': ['nombre'],
            },
        ),
    ]
