# Generated by Django 6.0.7 on 2026-08-06 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('esp32', 'ESP32'), ('relay', 'Modulo Relay'), ('pir', 'Sensor PIR')], default='esp32', max_length=20)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('api_key', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(choices=[('conectado', 'Conectado'), ('desconectado', 'Desconectado')], default='desconectado', max_length=20)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, default='1.0.0', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='laboratorio.laboratorio')),
            ],
            options={
                'verbose_name': 'Dispositivo ESP32',
                'verbose_name_plural': 'Dispositivos ESP32',
                'ordering': ['identificador'],
            },
        ),
        migrations.CreateModel(
            name='HistorialComunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('heartbeat', 'Heartbeat'), ('pir_dato', 'Dato PIR'), ('comando', 'Comando enviado'), ('respuesta', 'Respuesta recibida'), ('error', 'Error')], default='heartbeat', max_length=20)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('exitoso', models.BooleanField(default=True)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='dispositivos.dispositivo')),
            ],
            options={
                'verbose_name': 'Historial de comunicacion',
                'ordering': ['-recibido_en'],
            },
        ),
    ]
