# Generated by Django 6.0.6 on 2026-06-18 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorio', '0002_alter_laboratorio_options_laboratorio_creado_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('estado', models.CharField(choices=[('conectado', 'Conectado'), ('desconectado', 'Desconectado')], default='desconectado', max_length=20)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='laboratorio.laboratorio')),
            ],
            options={
                'verbose_name': 'Dispositivo ESP32',
                'verbose_name_plural': 'Dispositivos ESP32',
                'ordering': ['identificador'],
            },
        ),
        migrations.CreateModel(
            name='HistorialComunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='dispositivos.dispositivo')),
            ],
            options={
                'verbose_name': 'Historial de comunicación',
                'ordering': ['-recibido_en'],
            },
        ),
    ]
