# Generated by Django 6.0.2 on 2026-07-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Dirección MAC del ESP32 (ej: AA:BB:CC:DD:EE:FF)', max_length=17, null=True, unique=True),
        ),
    ]
